### ISSUE TITLE
Issues with editing z-matrix coordinates since e895aab

### ISSUE THREAD

**Issue by qma4** [brettbode/wxmacmolplt#108]
Since commit e895aab, the coordinate editor for Z-matrix seems to be broken on various Linux platforms (built from source code).  After clicking "subwindow->coordinate", changing the coord. type to "Z-matrix", and adding a few atoms, we encountered various issues on different platforms:

(1) on platform 1, after attempting to modify the type of atoms in the list, the type becomes "P" and cannot be further edited (modifying the text and it changes back to "P").

(2) on platform 2, the "length" cell of the second atom stays at 0.000000 and cannot be edited (clicking the cell does trigger the editing mode).

These problems are seen with the current master 9a46f7a, and can be fixed by reverting e895aab on both platforms.

Platform 1: An up-to-date 64-bit arch linux (Apr. 20, 2017) with wxgtk 3.0.2.  My colleagues have also encountered the same problem using fresh-compiled wxmacmolplt on openSUSE.
Platform 2: 64-bit Kubuntu 16.10.

**Comment by brettbode** [comment]
Hello,
   My apologies for taking so long to look at this issue. It has been a long time since I was able to put much time into the program.

I have identified two ways that cells would become locked when using  Z matrix mode in the coordinates window and checked in a fix for those issues. I am pretty sure they solve case 2, less sure about case 1. If you are still interested please let me know if you still encounter issues.

**Comment by brettbode** [comment]
Hello,
   I have just released version 7.7.2 which includes the fixes for the issue you reported. You can download the new binaries from the regular download page.
Best,
Brett
