### ISSUE TITLE
I want to install wxmacmolplot in my laptop : Ubuntu 12.04, i did not find the appropriate version for Ubuntu 12.04 to download from the website. Can anyone help me with this?

### ISSUE THREAD

**Issue by chandri22** [brettbode/wxmacmolplt#116]

**Comment by brettbode** [comment]
Hello,
  From the download page there is a binary available for debian/Ubuntu 12.04:

For Ubuntu 12.xx :
deb https://dl.bintray.com/brettbode/wxMacMolPlt-precise precise main
Then apt-get update. You should then be able to install using apt-get install wxmacmolplt for amd64 and i386 for the older architectures. I do not currently have a good way to host a debian source repo. If you would like to build your own debian bianry package grab the source tarball, unpack it. Change into the base wxmacmolplt directory and issue "debuild". You will have to have the dev-scripts package and other dependancies installed, but that will build a binary .deb package for the current architecture. Similarly you can use the wxMacMolPlt.rpm.spec file in the resources directory as input to rpmbuild to build a binary rpm package.
Note: Many newer Debian/Ubuntu distros are requiring signed packages by default. Since I do not have a recognized key these are unsigned so you may need to add "--allow-unauthenticated" to your apt-get command.

You can also grab the binary .deb file manually from:
https://dl.bintray.com/brettbode/wxMacMolPlt-precise/pool/main/w/wxmacmolplt/

Brett
