### ISSUE TITLE
Offsetted visualisation 

### ISSUE THREAD

**Issue by andre-cloud** [brettbode/wxmacmolplt#142]
### Please describe the problem or enhancement:

When opening any type of file, the geometry inside the window is completely off-set

### If this is a bug report please list the steps required to reproduce the problem:

Open a file

### What version of wxMacMolPlt are you running?

7.7.2

### What OS are you using? (please include 32/64 bit and if Linux the specific distribution)

Apple M1 Pro, 12.2.1

<img width="850" alt="Screen Shot 2022-08-01 at 10 58 30" src="https://user-images.githubusercontent.com/55535285/182112470-7c003183-49ee-41b7-b8aa-edf70ea4d21f.png">

**Comment by saromleang** [comment]
@andre-cloud a couple of options here since this looks like #137. Until it gets resolved you have some options:

Option 1
- connect an external monitor and move MacMolPlt visualization window to the external monitor

Option 2
- Un-install wxMacMolPlt 7.7.2 and install wxMacMolPlt 7.7 (64 bit only) instead [link](https://uofi.box.com/shared/static/ijfreodzydtqn214qui3snyvj5vdovqr.gz)

**Comment by andre-cloud** [comment]
Option 2 solved the problem. I won't close the issue, because it reports a bug of the new version, but thanks anyway

**Comment by brettbode** [comment]
It is definitely a bug. The issue with with high-resolution displays, either a retina display or a display that is "scaled" from its default resolution.

**Comment by brettbode** [comment]
I believe this issue is now resolved with the latest v7.7.3 release.
