### ISSUE TITLE
Is there interest for CI services ?

### ISSUE THREAD

**Issue by miroi** [brettbode/wxmacmolplt#89]
Hi Brett,

would you be interested in CI services (travis-ci, appveyor) incorporated into your code ?

These would make the derivative wxmacmolplt development more safe due to automatic checking of pull requests.

https://github.com/miroi/wxmacmolplt/blob/master/README.md

There are no self-tests yet (wxmacmolplt --self ?), at least it will check if the code compiles.

**Comment by brettbode** [comment]
Hello Miro,
   I can see how having an automated build environment would be useful and not too hard to put together. You are correct that I do not have much in the way of automated testing mostly due to the need for a graphics context to launch the program. How much effort is it to get a CI test for building the code? Does it cover multiple OS environments?

Thanks,
Brett

**Comment by miroi** [comment]
Hi Brett,

yes, CI services cover multiple environments and are important check of correctness for derivative code development. For open source, the usual scheme is travis-ci for linux + osx and appveyour for MS Windows.

In the case of graphics applications, as start it would be sufficient to get the application compiled and have the executable to do something without launching the graphics (graphics launching is usually not allowed on remote CI servers). 

I am going to prepare the pull request for travis-ci CI service from my fork.
