### ISSUE TITLE
Firefly811 issue: 1NSERCH keyword replaced by NSERCH keyword

### ISSUE THREAD

**Issue by catox0** [brettbode/wxmacmolplt#94]
### Please describe the problem or enhancement:
The new version of Gamess Firefly (Firefly811) replaced the keyword 1NSERCH with NSERCH when performing a geometry optimization. As a result, WxMacMolPlt does not read beyond the first geometry.

### If this is a bug report please list the steps required to reproduce the problem:
Run a geometry optimization in Firefly811, attempt to read the output file in WxMacMolPlt.

### What version are you running?
WxMacMolPlt v.7.5
WxMacMolPlt v.7.62

### What OS are you using? (please include 32/64 bit and if Linux the specific distribution)
Windows 8, 64-bit

**Comment by brettbode** [comment]
The current version of GAMESS does not use "1NSERCH" replacing it with a string: "BEGINNING GEOMETRY SEARCH POINT NSERCH=". "NSERCH" by itself is not a unique keyword so if that is all that Firefly is using now it would require other reengineering to track.

I do not generally support FireFly since it is an unauthorized fork of GAMESS.

**Comment by catox0** [comment]
I found an alternative solution to the problem:
Adding the command line option -legacy will revert the Gamess Firefly output to one that is legible by wxmacmolplt.

Thanks goes to Alex Granowsky who pointed this out.

**Comment by brettbode** [comment]
Interesting option. I will add it to my known issues/work arounds page.
